export interface IBookingItem {
  voucherModel: VaucherModelType;
  createDate?: any;
  createUserID?: any;
  state?: any;
  partNumber?: string;
  serialNumber?: string | number;
  batchNumber?: string | number;
  owner?: string;
  history_number?: number;
  quantity?: any;
  price?: any;
  currency?: any;
  store?: any;
  projectID?: string;
  orderNumber?: any;
  location?: string;
  station?: string;
  userID: string;
  userSing: any;
  companyID: string;
  partGroup?: string;
  partType?: string;
  condition?: string;
  description?: string;
  addDescription?: string;
  registrationNumber?: any;
  planeType?: any;
  customer?: any;
  projectWO?: any;
  workshop?: any;
  additionalTaskID?: string;
  projectTaskWO?: string;
  label?: any;
  receivingNumber?: any;
  receivingItemNumber?: any;
  suppliesCode?: any;
  suppliesId?: any;
  orderId?: string;
  orderType?: string;
  IS_CUSTOMER_GOODS?: boolean;
  PART_NUMBER?: string | number;
  NAME_OF_MATERIAL?: string;
  QUANTITY?: any;
  GROUP?: string;
  TYPE?: string;
  CONDITION?: string;
  SHELF_NUMBER?: string;
  STOCK?: string;
  OWNER?: string;
  PRICE?: any;
  RECEIVED_DATE?: Date;
  PART_REMARKS?: any;
  ORDER_NUMBER?: any;
  UNIT_OF_MEASURE?: string;
  CURRENCY?: any;
  COMPANY_ID?: any;
  SUPPLIER_BATCH_NUMBER?: any;
  SUPPLIES_CODE?: string;
  SUPPLIES_LOCATION?: string;
  SUPPLIER_NAME?: string;
  SUPPLIER_SHORT_NAME?: string;
  SUPPLIER_UNP?: any;
  SUPPLIES_ID?: any;
  IS_RESIDENT?: boolean;
  ADD_UNIT_OF_MEASURE?: string;
  ADD_NAME_OF_MATERIAL?: string;
  ADD_PART_NUMBER?: any;
  ADD_QUANTITY?: any;
  OWNER_SHORT_NAME?: string;
  OWNER_LONG_NAME?: string;
  PRODUCT_EXPIRATION_DATE?: Date;
  WAREHOUSE_RECEIVED_AT?: any;
  SERIAL_NUMBER?: any;
  APPROVED_CERT?: any;
  AWB_REFERENCE?: any;
  AWB_TYPE?: any;
  AWB_NUMBER?: any;
  AWB_DATE?: Date;
  RECEIVING_NUMBER?: any;
  RECEIVING_ITEM_NUMBER?: any;
  CERTIFICATE_NUMBER?: any;
  CERTIFICATE_TYPE?: string;
  REVISION?: 'C' | 'B' | 'A';
  LOCAL_ID?: string;
  ORDER_ID?: string;
  ORDER_TYPE?: string;
  receivingGoodsId?: string;
  STATUS?: string;
  PART_RECEIVING_REMARKS?: string;
  PART_PICKSLIP_REMARKS?: string;
  PART_REPARE_REMARKS?: string;
  PART_PURCHASE_REMARKS?: string;
  pickDate?: any;
  pickSlipNumber?: any;
}
type VaucherModelType =
  | 'ADD_NEW_PART'
  | 'STORE_TO_A/C'
  | 'CHANGE_LOCATION'
  | 'AC_TYPE_CHANGE'
  | 'STORE_TO_SHOP'
  | 'RECEIVING_GOODS'
  | 'RECEIVING_CANCELLED'
  | 'BATCH_CHANGE'
  | 'ADD_ROTABLES'
  | 'BACK_TO_STORE'
  | 'COMPONENT_INSPECTION'
  | 'RETURN_DELIVERY'
  | 'DELETE_REQUIREMENT'
  | 'A/C_TO_STORE'
  | 'ENTITY_CHANGE'
  | 'SHOP_TO_STORE'
  | 'EXCHANGED'
  | 'INCOMING_SHIPMENT_ARRIVED'
  | 'INTERVAL_REMOVED'
  | 'KIT_TRANSFER'
  | 'INVOCE_DETAIL_BOOKED'
  | 'MAT_CLASS_CHANGE'
  | 'MODIFIED'
  | 'OWNER_CHANGE'
  | 'PART_ACTIVATED'
  | 'PART_DEACTIVATED'
  | 'UNIT_CHANGE'
  | 'AV_PRICE_CHANGE'
  | 'QUARANTINE'
  | 'PART_NUMBER_CHANGE'
  | 'PART_RESERVATION'
  | 'QTY_CHANGE'
  | 'STOCK_PURCHASE'
  | 'SCRAP'
  | 'SHELF_INSPECTION'
  | 'S/N_CHANGE'
  | 'TRANSFER'
  | 'TRANSFER_CANCELLED'
  | 'TRANSFER_RECEIVE'
  | 'TRANSFER_SHIP'
  | 'TOOL_TRANSFER'
  | 'TOOL_LOST_NOTICE'
  | 'VENDOR_INSTALATION'
  | 'INCOMING_SHIPMENT_SENT'
  | 'OUTGOIN SHIPMENT ARRIVED';
