export interface IBookingItem {
  createDate: Date;
  voucherModel: VaucherModelType;
  partNumber: string;
  serialNumber?: string | number;
  batchNumber?: string | number;
  owner?: string;
  history_number?: number;
  quantity?: any;
  price?: any;
  currency?: any;
  store?: any;
  projectID?: string;
  orderNumber?: any;
  location?: string;
  station: string;
  userID: string;
  userSing: any;
  companyID: string;
  partGroup?: string;
  partType?: string;
  condition?: string;
  description?: string;
  addDescription?: string;
  registrationNumber?: any;
  planeType?: any;
  projectWO?: any;
  workshop?: any;
  additionalTaskID?: string;
  projectTaskWO?: string;
  label?: any;
  receivingNumber?: any;
  receivingItemNumber?: any;
}
type VaucherModelType =
  | 'ADD_NEW_PART'
  | 'STORE_TO_A/C'
  | 'CHANGE_LOCATION'
  | 'AC_TYPE_CHANGE'
  | 'STORE_TO_SHOP'
  | 'RECEIVING_GOODS'
  | 'RECEIVING_CANCELLED'
  | 'BATCH_CHANGE'
  | 'ADD_ROTABLES'
  | 'BACK_TO_STORE'
  | 'COMPONENT_INSPECTION'
  | 'RETURN_DELIVERY'
  | 'DELETE_REQUIREMENT'
  | 'A/C_TO_STORE'
  | 'ENTITY_CHANGE'
  | 'SHOP_TO_STORE'
  | 'EXCHANGED'
  | 'INCOMING_SHIPMENT_ARRIVED'
  | 'INTERVAL_REMOVED'
  | 'KIT_TRANSFER'
  | 'INVOCE_DETAIL_BOOKED'
  | 'MAT_CLASS_CHANGE'
  | 'MODIFIED'
  | 'OWNER_CHANGE'
  | 'PART_ACTIVATED'
  | 'PART_DEACTIVATED'
  | 'UNIT_CHANGE'
  | 'AV_PRICE_CHANGE'
  | 'QUARANTINE'
  | 'PART_NUMBER_CHANGE'
  | 'PART_RESERVATION'
  | 'QTY_CHANGE'
  | 'STOCK_PURCHASE'
  | 'SCRAP'
  | 'SHELF_INSPECTION'
  | 'S/N_CHANGE'
  | 'TRANSFER'
  | 'TRANSFER_CANCELLED'
  | 'TRANSFER_RECEIVE'
  | 'TRANSFER_SHIP'
  | 'TOOL_TRANSFER'
  | 'TOOL_LOST_NOTICE'
  | 'VENDOR_INSTALATION'
  | 'INCOMING_SHIPMENT_SENT'
  | 'OUTGOIN SHIPMENT ARRIVED';
