name: Build

on:
  push:
    branches: [develop]
    paths-ignore:
      - "**.md"
      - "**.spec.js"
      - ".idea"
      - ".vscode"
      - ".dockerignore"
      - "Dockerfile"
      - ".gitignore"
      - ".github/**"
      - "!.github/workflows/build.yml"

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Install canvas for Electron (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          npm install --global --production windows-build-tools
          npm install --global node-gyp
          npm install canvas@2.11.2 --build-from-source
        shell: powershell

      - name: Install canvas for Electron (macOS/Linux)
        if: matrix.os != 'windows-latest'
        run: npm install canvas@2.11.2 --build-from-source

      - name: Build
        run: npm run build
        env:
          NODE_OPTIONS: --max-old-space-size=8192
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: release_on_${{ matrix.os }}
          path: release
          retention-days: 5