name: Release
on:
  push:
    branches:
      - test-realese

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev build-essential
          sudo apt-get install -y python3-pip

      - name: Install Dependencies
        run: |
          npm ci
          npm config set canvas_binary_host_mirror https://github.com/Automattic/node-canvas/releases/download/
          npm rebuild canvas --update-binary

      - name: Build
        env:
          NODE_OPTIONS: --max-old-space-size=8192
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES: true
        run: |
          npm run build
          npm run electron:build

      - name: Create Release
        if: matrix.os == 'ubuntu-latest'
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: v${{ steps.package-version.outputs.version }}
          name: Release v${{ steps.package-version.outputs.version }}
          draft: false
          prerelease: false
          files: |
            release/**/*.AppImage
            release/**/*.deb
            release/**/*.exe
            release/**/*.dmg
            release/**/*.zip
            release/**/*.yml
