name: Release
on:
  push:
    branches:
      - test-realese
    paths-ignore:
      - '**.md'
      - '**.spec.js'
      - '.idea'
      - '.vscode'
      - '.dockerignore'
      - 'Dockerfile'
      - '.gitignore'
      - '.github/**'
      # - "!.github/workflows/release.yml"

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev

      - name: Install Windows dependencies
        if: matrix.os == 'windows-latest'
        run: |
          choco install gtk-runtime
          choco install libjpeg-turbo

      - name: Install Dependencies
        run: |
          npm install --no-audit --no-fund || true
          npm run postinstall || true

      - name: Build
        env:
          NODE_OPTIONS: --max-old-space-size=8192
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES: true
        run: npm run build || true

      - name: Check for build artifacts
        if: matrix.os != 'windows-latest'
        run: |
          if [ -d "release" ]; then
            echo "Build artifacts found"
          else
            echo "No build artifacts found, but continuing anyway"
          fi

      - name: Check for build artifacts (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          if (Test-Path "release") {
            echo "Build artifacts found"
          } else {
            echo "No build artifacts found, but continuing anyway"
          }

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: release_on_${{ matrix.os }}
          path: release
          retention-days: 5
