name: Release
on:
  push:
    branches: [feature/formatedInputs]
    paths-ignore:
      - '**.md'
      - '**.spec.js'
      - '.idea'
      - '.vscode'
      - '.dockerignore'
      - 'Dockerfile'
      - '.gitignore'
      - '.github/**'
      # - '!.github/workflows/build.yml'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev build-essential g++

      - name: Install Windows dependencies
        if: matrix.os == 'windows-latest'
        run: |
          choco install gtk-runtime
          choco install libjpeg-turbo

      - name: Install Dependencies
        run: |
          npm install --no-audit --no-fund
          npm run rebuild

      - name: Build
        run: npm run build
        env:
          NODE_OPTIONS: --max-old-space-size=8192
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: release_on_${{ matrix.os }}
          path: release
          retention-days: 5
